[package]
name = "tama_headless"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[build-dependencies]
cc = "1"
